---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: "v1.8.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
    webhook:
      enabled: true
    replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "8.8.4.4"
        - "8.8.8.8"
