---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ctnr-cloud-wildcard-prod
  namespace: traefik
spec:
  secretName: ctnr-cloud-wildcard-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.ctnr.cloud"
    - "ctnr.cloud"
