apiVersion: v1
kind: Secret
metadata:
    name: thetagang-notifications-secret
    namespace: thetagang
data:
    WEBHOOK_URL_EARNINGS: ENC[AES256_GCM,data:vnwQiQyd3PxdJj1z3vAis/faQbtk2MxosCtzg+wjKNbwqvVhn42xZJBVJz128RK/exa8hAX7JOySke05N1PyNH2bibvLeya2l7cAsiyokDcqSPtIpNIDvgwA9T/sr486Xuygx1bZ99vKGIhyfOE6pHtCIW3KBzMg/Vr5EnKOJb066xeAjb/O3IkN/9fz4iFmueIRnatX/19xDLEVX0IGU/7Y5xY=,iv:iB06B/myDvN0LubMopTuc97Nz1jewQD2Q53RdGahgCI=,tag:nTE4XLCleI0ShEW1tOITPg==,type:str]
    WEBHOOK_URL_TRADES: ENC[AES256_GCM,data:cBNBiSre94shfEn8Fh41VdCLwOvMbsDxVAdy1cXqg0Lgvgkt2iTBwA1yhX+B9/ow8WipCqgj5mku/R9wfUzNvGWdtkthCQxrPlVg2VJ0xm/WIRfZvef+zym3vdOq1/MVz49ONqhtHYzZLZJVT4SrUozFnb7osOTvnHVtxtUi5hP4JYgsYPk6lVFCcFd2jQwHA24WVP2u3evNtPXZszYAxwt6Xik=,iv:MJKv7xdMh41Pmv/sLHUo8VsP5yfhRrU6NwX1etAyt6k=,tag:C+uKYERf2pdJ2U78HeYeAg==,type:str]
    WEBHOOK_URL_TRENDS: ENC[AES256_GCM,data:E00B8+J5fsSC2BJlTaO0GofhOABVzImkg7XQiiWaoY+oDUizTDWazm2GhXdbJNfYRwYUM4BTpZ3D0C/wa2uzMYbwMEv4gTBZ/9ZWkMErW/hQqkSJZo4VeNjaVqs66gRT8fgE16RwCVm90mhjnlXqpBRUBCAZrrVOJJ+d915ptGbCCXa9/iNKHevYWWTKdCUvNw5PxqBFj02dvrCjlRtKxahdKyw=,iv:A7QByBat7DvZZJpEv3f2hCu6VCoUMknn0tJXTJWq9Y4=,tag:lfn8K2PDsd0gcY8oypFTBg==,type:str]
    TWITTER_CONSUMER_KEY: ENC[AES256_GCM,data:qAdKu1cQ+6gQ4FP1ceyAATb2I+q3gX0Eh+m5hhb/u5FaTak9,iv:8VU1uKH1qCRkLZ2PwzSpVh3+YgUemv++Iw+SPd914Kc=,tag:Lbdfnkr6l1NG7YFcMs3w1Q==,type:str]
    TWITTER_CONSUMER_SECRET: ENC[AES256_GCM,data:RPE/2yMQXfi8HXEA4JIGemLgn5jEt/XhA0spouViemwQMszBU4zuOmRew22TNavZcOzSnUp0f8ulBeBqHRlLlL8jhbA=,iv:rqc7KgitQ4x+Yf2jwVKrbpdopHn5rXql6YQlDTK0HWw=,tag:M2rGcIuerqw7aRD/s+Cqzg==,type:str]
    TWITTER_ACCESS_TOKEN: ENC[AES256_GCM,data:IahxNy152JdpPZbnP8eNs0Y8DQOKiIPNj9JurvPYedIuZT+s+5STprgVjH7Yq8JuNMO6bsuFb0Jr1vFP6b70UcV/uvY=,iv:b4ohK6n2/QY5Px+jTdgbxWlViDAP+qCOXqBsYgWFyLc=,tag:VBNSn02YUOizWH8iq6m3lA==,type:str]
    TWITTER_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:DZYJvNdOgH5D7aXOU3bdPdhFoX8Z2pQ/zVheRgwcoxEJALYGnzYvXikSNeDeFRIs13Un9BXd0Lpof1Kd6KGIpkg=,iv:ysU5NBgHthM4fhaeoQyRe4oVfE10f6AqvLXZHVRkQZc=,tag:ObDIt1D8C6v9WjB5FvJUzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8dts3ptgqsqac60z8v2asney6akyktad43k5reguj5suj6y83rstgyh8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ1VFVHA0aUY4ZW82ZVYw
            ejgvMkxuSVMyYmt4c3Z1RzEzZ3g4QkRUZ1NRClg1aXpvOE1HNXJjaGN1MDlkKzlG
            d2Vodzl0YTFEVVR4bnlqMVJGU05pck0KLS0tIE1sMW1oU3R0Q3pOdUhxa1dzMSt2
            bWFXWVRta2M3eHcyNTJPSXYwdUl1T2cKrKSmVzkt0PHnZlNdOzM5Y88L3apxjUsH
            2DKEIw0UVT6ICf+QKhAv6JLpXZlxRrhc7RYsBLRlQo0hKxZyMYrFEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-11T16:52:56Z"
    mac: ENC[AES256_GCM,data:4byitlyspVaO31MkAWHdGhNRdb8YmYjipSueVQemHWbw5m4hflQm9om9aR4dYCAn9JU+hyKT5Ck756KZ4EF4wRjmA20Kq/08kmTtU0isONehE7LYnn8lIfwiYnhb7A29E/DuqxcmiIORc98fKUlLiIf+cR5dLTwN/aLweCnC//c=,iv:V7Nf0kT7yMemUg7Bfm5oGbxWNrpmCa+DUyoggeYV5j0=,tag:o5yKfT7RajPlhRA1khiD4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
