---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: botkube
      version: "v0.12.4"
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
  # https://www.botkube.io/installation/discord/
  values:
    communications:
      discord:
        enabled: true
        channel: 909901631347367991
        botid: 957998470076170320
        notiftype: short
    config:
      settings:
        clustername: do
      kubectl:
        enabled: false
  valuesFrom:
    - secretKeyRef:
        name: discord-secret
        namespace: botkube
        key: values.yaml
        optional: false
