---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: matrix
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: postgresql
      version: "11.1.12"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  values:
    primary:
      persistence:
        size: 10Gi
        storageClass: do-block-storage
    readReplicas:
      replicaCount: 0
