apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:lRIXsQ761g7L3smd0MnUxXFsMRzH6lLuy3OOPmrM+HAQ/kYdg8SGGw7Ss/uE6AGtw7YEuotJdAKJHYIGIQK9PuDFtWESidG61ZDBFJYIxcAMsXHZvBm/ykYDJ6aFhNP+/3zw/vlj1e0tMG4NrNnoXfHxHVdXlTbztdLsql+e3keKQ+d5EQ5XCJ9/lv2mmBqR/ziM+FWNKyaIUR6vHTrTamEibYZSb/5l4ec43oyqhWYw0i7pZvIpf0SribKaG00TvdGL5GlxcjF2r4Ff4UQZPZKsEGNHT2yxJCGmOQ1eCHv87edVCjnttLQY+WYh/4YRXtfEhDYapYMBVgaDpN8q1fDElR8ZuBVi4Tb6pCcnZIAwUKy5UuTdxNJbWxf+egSl0TSQPm/Fwou26+ow1yBPWrvpvyq3JcsynirjwuotvJWSPhiiePzIqVnJ+5AA2Ew5khzC1vkAX3eGY3UF5w1aRQexJO95+qHkuYi0hJmXqrKZdedkt3l+dzSp3oor5a3MYxLSGNsxdcvs8UNlOxMHvUg7wNuLPG/I5CzOHsnQynyCbfSzD8JaPy2pVdPq16JFdqTlOxJxMnvdEKkiMKBGbjhjCZu1Fsv0T9iCxsz29LTb0BBU2bix1mAIxgQOIj5kWP46W1oDyJRxPTNf6Du6lp3rcqjF61DyBMKr1R8rltDihXtUOpRi6yvOtxau+E5r1AALRr2uF2VxwvGAkjNnRm3Ej8REYvtjACgmf0yx981xcWxO+FaROeYVG1dmAv7lGtT7WmIXSyJWfholz+Ck//0r/186Zun2PS68R7oS2TDb2b/QcLVGO9CWv1YMA5/RPaz7+qQ6YGloryV+uM3QBEAJYkQsBUNj6TL8Vmx1z3kC+1z6mkVDyreHGAjyskNuHFh/66V5WNdjzKr6HDuzy3kn916dbjdyUQI23MqJzfw41Gxy6HmRzvgjkf4KvfvQvEfZgFCzPNqCtjcvk8fCXio1xwKzeNdVet0HRCLKqxbzYiWXw7REUEqFu9XZKUZofxyPKvFxySY6FZmEgZlWXp91Uvdggngd0R6txKBAzhLdc+mexnFTs4G9gPm+mMnx75CV4h6iEfQWyiZjZEGCaM9+1b/VLJr9mJMpsbXSdsNtiV6idHfXuskrCWH5ELk/2mQBEPG/D1k1eT1XLBnjS23q5xAnaBMFzyDCaJoHryZzdA8o/lXfZQ36rfzZyPHRXg/eIZONjcKipAZ+79cAf46BtuZRlXl7ymjS4vtw7sA7/lgxgGWxPrgpK6uppP2nQ3ADJ+1jAlvz0Pc88rwT8i/5LMWWrSoivnHvmKrF3Y3ndv8EzfdSW7zFxeeOfSoWWSw5msqSr4pPtjjj/I+xiiaco+LZyyDTTwSCz1BeMqtnszDvQEQ1pFH12AUfupYKggL3jk3t3YuIofh2GGyLrCg02Q0xD4/NonF5RqwmWbECPSMNGeM+5TFHV/6v+0E06mgfB32B3FN5gvTOhotxGsdKBrSvvCSYJFVKdMMoijagTicKoEa8vvZohyE4GLmh68tbt39BFTu+Klyy/AeYscFDgMdnHGzZTJ9B3VWQpm6fRvhNYqaH9NYmfqtkNiT1Kx6LfIpf0/qt1Vx3gy+6MjqFrW83xiFBtV/xgVsVTY3t7EUQc+m34PVlv2C3316M80E6DTh3wc/QIByrWl8x4Kmr56ik9jFdHMDR1cRLp7fD1TJR6fk59ckrTpLVkgRhCzPyqk3WVue08AytoDNxdiYwZJV930GFuQNHug==,iv:tki6WKQ5RQoPbJuNIVG6Toexr5bUf2iIzRpHueB4y+k=,tag:wUn7LqtPjvECcjPO0m8t/w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: postgresql-secret
    namespace: matrix
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8dts3ptgqsqac60z8v2asney6akyktad43k5reguj5suj6y83rstgyh8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWWdJZ2NYU0lBcXdpdU5P
            Y0s0U1grV0pjTk1yZUlrVVlJb01BK0JEV25VClMvZE5OMlNMS3RuRFlmQndmZjRI
            blRvUzFTVjdNaEczU1NjWjZtWHJOVkUKLS0tIGtKaUtqYzg3SkI4WkZBYTY4dnJY
            cEM4L2J6dmVwMjRkVUpINFIwS0ZFeXcKPZvLxcrdpHWV9Cl0RpUvbYBCI54gAmfi
            wnhW3BRUgQtM/N48d8W9jCHZpVTKp1l+ALQrMMyndSbty0LfTCXiaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T19:34:19Z"
    mac: ENC[AES256_GCM,data:+XYG9MhlkEEny9rJBz/02hMuyEHCWQdRED3I8UvmE24buM9Vq7RF+a48ozYBfmCzXiigXe0+LcQhj7Jit8k6CTvNuxS840xMXfT0dhgQr3piigVHvDUZipkAKd2h82PDVm++2DXj+++qRFXHH/mRi/TEetRldyylOvHFtI+v944=,iv:XOa6cVs9Mk1K9X6ouFm1Wdgy2Lja29n+qU2i4sWI/kQ=,tag:LLs8Z8KXbDueC5rbCBBQKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
