apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-postgres
  namespace: matrix
spec:
  selector:
    matchLabels:
      app: matrix-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: matrix-postgres
    spec:
      containers:
        - name: matrix-postgres
          image: docker.io/library/postgres:14
          # volumeMounts:
          #   - mountPath: "/var/lib/postgresql/data"
          #     name: matrix-postgres
          env:
            - name: POSTGRES_DB
              value: synapse
  # volumeClaimTemplates:
  #   - metadata:
  #       name: matrix-postgres
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 10Gi
  #       storageClassName: do-block-storage
